language: python
sudo: false
matrix:
  include:
    - os: windows
      language: sh
      before_install:
        - choco install pyenv-win --yes
        - pyenv --version
        - type .python-version
        - pyenv install -q .python-version
        - pip install -r requirements_dev.txt

script:
  - "PYTHONPATH=. pytest -v -s --cov=pyenv-win tests"

after_success:
  - coveralls

