language: python
sudo: false
os:
  - windows

install:
  - pyenv install .python-version
  - pip install -r requirements_dev.txt

script:
  - "PYTHONPATH=. pytest -v -s --cov=pyenv-win tests"

after_success:
  - coveralls

