name: pytest

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: pyenv-win pytest
    runs-on: windows-latest
    env:
      HOME: D:\a\.pyenv
    steps:
      - name: create pyenv workspace
        run: | 
          mkdir -p ${{ env.HOME }}

      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ../../.pyenv

      - name: pytest bash script
        run: ${{ env.HOME }}/.github/scripts/build.sh
        shell: bash
